///Below enums are used for determining tutorial progress
enum TutorialStepEnums{
  START_TUTORIAL_VIEW,
  START_GHOST_INTRODUCTION,
  SPAWN_GHOST,
  START_COIN_INTRODUCTION,
  SPAWN_COIN,
  ADDITIONAL_GAME_COLLECTIBLES,
  START_ACTUAL_GAME
}
